/**
 * Simple Demo of YouTube API Functionality
 * 
 * Run with: node demo-youtube.js
 * 
 * Shows a clean demo of working features
 */

import * as youtubeApi from './youtube-api.js';
import * as transcriptFetcher from './transcript-fetcher.js';

console.log('\n═══════════════════════════════════════════════════');
console.log('   📺 Phase 8: YouTube Video Intelligence Demo');
console.log('═══════════════════════════════════════════════════\n');

// Demo with a short educational video
const DEMO_VIDEO = 'https://www.youtube.com/watch?v=UvI-AMAtrvE'; // Khan Academy (8 min)

async function runDemo() {
  try {
    console.log('Testing with Khan Academy video...\n');
    
    // 1. Get video metadata
    console.log('1️⃣  Fetching video metadata...');
    const metadata = await youtubeApi.getVideoMetadata(DEMO_VIDEO);
    console.log(`   ✅ Title: "${metadata.title}"`);
    console.log(`   ✅ Author: ${metadata.author}`);
    console.log(`   ✅ Duration: ${metadata.durationFormatted}`);
    console.log(`   ✅ Views: ${youtubeApi.formatViewCount(metadata.viewCount)}`);
    console.log(`   ✅ URL: ${metadata.url}\n`);
    
    // 2. Check caption availability
    console.log('2️⃣  Checking caption availability...');
    const captions = await youtubeApi.checkCaptionAvailability(DEMO_VIDEO);
    if (captions.available) {
      console.log(`   ✅ Captions available in ${captions.languages.length} languages`);
      console.log(`   Languages: ${captions.languages.slice(0, 3).map(l => l.name).join(', ')}...`);
      console.log(`   Auto-generated: ${captions.hasAutoGenerated ? 'Yes' : 'No'}\n`);
    }
    
    // 3. Fetch transcript
    console.log('3️⃣  Fetching video transcript...');
    const transcript = await transcriptFetcher.getTranscript(DEMO_VIDEO);
    console.log(`   ✅ Language: ${transcript.metadata.languageName}`);
    console.log(`   ✅ Segments: ${transcript.metadata.segmentCount}`);
    console.log(`   ✅ Words: ${transcript.metadata.wordCount.toLocaleString()}`);
    console.log(`   ✅ Duration: ${transcriptFetcher.formatTimestamp(transcript.metadata.totalDuration)}\n`);
    
    // 4. Show first few lines
    console.log('4️⃣  First 5 lines of transcript:');
    for (let i = 0; i < Math.min(5, transcript.segments.length); i++) {
      const seg = transcript.segments[i];
      console.log(`   [${seg.timestamp}] ${seg.text}`);
    }
    console.log('');
    
    // 5. Get statistics
    console.log('5️⃣  Transcript statistics:');
    const stats = transcriptFetcher.getTranscriptStats(transcript);
    console.log(`   Avg words per segment: ${stats.avgWordsPerSegment}`);
    console.log(`   Sentence count: ${stats.sentenceCount}`);
    console.log(`   Estimated reading time: ${stats.estimatedReadingTime} minutes\n`);
    
    // 6. Search within transcript
    console.log('6️⃣  Searching for keyword "slope"...');
    const searchResults = transcriptFetcher.searchTranscript(transcript, 'slope', false);
    console.log(`   ✅ Found ${searchResults.length} matches`);
    if (searchResults.length > 0) {
      const first = searchResults[0];
      console.log(`   First match at ${first.match.timestamp}:`);
      console.log(`   "${first.match.text}"\n`);
    }
    
    // 7. Chunk for AI processing
    console.log('7️⃣  Chunking transcript for AI analysis...');
    const chunks = transcriptFetcher.chunkTranscript(transcript, 60);
    console.log(`   ✅ Created ${chunks.length} chunks (60s max each)`);
    console.log(`   Chunk 1: [${chunks[0].timestamp}] ${chunks[0].segmentCount} segments, ${chunks[0].text.split(' ').length} words`);
    console.log(`   Chunk 2: [${chunks[1].timestamp}] ${chunks[1].segmentCount} segments, ${chunks[1].text.split(' ').length} words\n`);
    
    console.log('═══════════════════════════════════════════════════');
    console.log('   ✅ All features working perfectly!');
    console.log('   Ready to build UI integration.');
    console.log('═══════════════════════════════════════════════════\n');
    
  } catch (error) {
    console.error('\n❌ Error:', error.message);
    console.error(error);
    process.exit(1);
  }
}

runDemo();
