/**
 * Test YouTube API and Transcript Fetcher
 * 
 * Run with: node test-youtube.js
 * 
 * Tests video metadata extraction and transcript fetching
 * with various types of YouTube videos
 */

import * as youtubeApi from './youtube-api.js';
import * as transcriptFetcher from './transcript-fetcher.js';

// Test videos (various lengths and types)
const TEST_VIDEOS = [
  {
    name: 'Short educational video',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', // Rick Astley - Never Gonna Give You Up
    expectedDuration: 213 // ~3:33
  },
  {
    name: 'Khan Academy video',
    url: 'https://www.youtube.com/watch?v=UvI-AMAtrvE', // Introduction to Slope
    expectedDuration: 514 // ~8:34
  },
  {
    name: 'CrashCourse video',
    url: 'https://www.youtube.com/watch?v=3GwjfUFyY6M', // Mesopotamia
    expectedDuration: 730 // ~12:10
  }
];

/**
 * Test video URL parsing
 */
async function testUrlParsing() {
  console.log('\n🧪 Testing URL Parsing...\n');
  
  const urls = [
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'https://youtu.be/dQw4w9WgXcQ',
    'https://www.youtube.com/embed/dQw4w9WgXcQ',
    'dQw4w9WgXcQ',
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=30s'
  ];
  
  for (const url of urls) {
    const videoId = youtubeApi.extractVideoId(url);
    const isValid = youtubeApi.isValidVideoId(videoId);
    console.log(`✓ ${url}`);
    console.log(`  → Video ID: ${videoId} (valid: ${isValid})\n`);
  }
  
  // Test invalid URLs
  const invalidUrls = [
    'https://www.google.com',
    'not a url',
    '',
    null
  ];
  
  console.log('Testing invalid URLs:');
  for (const url of invalidUrls) {
    const videoId = youtubeApi.extractVideoId(url);
    console.log(`✓ ${url} → ${videoId === null ? 'null (correct!)' : 'ERROR: should be null'}`);
  }
}

/**
 * Test video metadata fetching
 */
async function testMetadataFetching() {
  console.log('\n🧪 Testing Metadata Fetching...\n');
  
  for (const video of TEST_VIDEOS) {
    console.log(`\n📹 ${video.name}`);
    console.log(`URL: ${video.url}\n`);
    
    try {
      const metadata = await youtubeApi.getVideoMetadata(video.url);
      
      console.log(`✓ Title: ${metadata.title}`);
      console.log(`✓ Author: ${metadata.author}`);
      console.log(`✓ Duration: ${metadata.durationFormatted} (${metadata.duration}s)`);
      console.log(`✓ Views: ${youtubeApi.formatViewCount(metadata.viewCount)}`);
      console.log(`✓ Upload Date: ${metadata.uploadDate}`);
      console.log(`✓ Category: ${metadata.category || 'N/A'}`);
      console.log(`✓ Thumbnails: ${Object.keys(metadata.thumbnails).length} sizes`);
      console.log(`✓ Live: ${metadata.isLiveContent ? 'Yes' : 'No'}`);
      
      // Check caption availability
      const captions = await youtubeApi.checkCaptionAvailability(video.url);
      console.log(`✓ Captions available: ${captions.available ? 'Yes' : 'No'}`);
      if (captions.available) {
        console.log(`  Languages: ${captions.languages.map(l => l.name).join(', ')}`);
        console.log(`  Auto-generated: ${captions.hasAutoGenerated ? 'Yes' : 'No'}`);
        console.log(`  Manual: ${captions.hasManual ? 'Yes' : 'No'}`);
      }
      
    } catch (error) {
      console.error(`✗ Error: ${error.message}`);
    }
  }
}

/**
 * Test transcript fetching
 */
async function testTranscriptFetching() {
  console.log('\n🧪 Testing Transcript Fetching...\n');
  
  for (const video of TEST_VIDEOS) {
    console.log(`\n📹 ${video.name}`);
    console.log(`URL: ${video.url}\n`);
    
    try {
      // Get available languages first
      const languages = await transcriptFetcher.getAvailableLanguages(video.url);
      console.log(`✓ Available languages: ${languages.map(l => `${l.name} (${l.code})`).join(', ')}\n`);
      
      // Fetch transcript
      const transcript = await transcriptFetcher.getTranscript(video.url);
      
      console.log(`✓ Transcript metadata:`);
      console.log(`  Language: ${transcript.metadata.languageName} (${transcript.metadata.language})`);
      console.log(`  Auto-generated: ${transcript.metadata.isAutoGenerated ? 'Yes' : 'No'}`);
      console.log(`  Segments: ${transcript.metadata.segmentCount}`);
      console.log(`  Duration: ${transcriptFetcher.formatTimestamp(transcript.metadata.totalDuration)}`);
      console.log(`  Words: ${transcript.metadata.wordCount.toLocaleString()}`);
      console.log(`  Characters: ${transcript.metadata.characterCount.toLocaleString()}`);
      
      // Show first few segments
      console.log(`\n✓ First 3 segments:`);
      for (let i = 0; i < Math.min(3, transcript.segments.length); i++) {
        const seg = transcript.segments[i];
        console.log(`  [${seg.timestamp}] ${seg.text}`);
      }
      
      // Get statistics
      const stats = transcriptFetcher.getTranscriptStats(transcript);
      console.log(`\n✓ Statistics:`);
      console.log(`  Avg words per segment: ${stats.avgWordsPerSegment}`);
      console.log(`  Avg segment duration: ${stats.avgSegmentDuration}s`);
      console.log(`  Sentence count: ${stats.sentenceCount}`);
      console.log(`  Estimated reading time: ${stats.estimatedReadingTime} minutes`);
      
      // Test chunking
      const chunks = transcriptFetcher.chunkTranscript(transcript, 30);
      console.log(`\n✓ Chunked into ${chunks.length} sections (30s max each)`);
      console.log(`  First chunk: [${chunks[0].timestamp}] "${chunks[0].text.substring(0, 100)}..."`);
      
    } catch (error) {
      console.error(`✗ Error: ${error.message}`);
    }
  }
}

/**
 * Test transcript search
 */
async function testTranscriptSearch() {
  console.log('\n🧪 Testing Transcript Search...\n');
  
  const video = TEST_VIDEOS[1]; // Khan Academy video
  console.log(`📹 ${video.name}`);
  console.log(`URL: ${video.url}\n`);
  
  try {
    const transcript = await transcriptFetcher.getTranscript(video.url);
    
    // Search for common educational terms
    const searchTerms = ['slope', 'line', 'graph'];
    
    for (const term of searchTerms) {
      const results = transcriptFetcher.searchTranscript(transcript, term, false);
      console.log(`✓ Search for "${term}": ${results.length} results`);
      
      if (results.length > 0) {
        const first = results[0];
        console.log(`  First match at ${first.match.timestamp}: "${first.match.text}"`);
      }
    }
    
    // Test segment retrieval
    const testTime = 30; // 30 seconds in
    const segment = transcriptFetcher.getSegmentAtTime(transcript, testTime);
    console.log(`\n✓ Segment at ${testTime}s: "${segment?.text || 'Not found'}"`);
    
    // Test range retrieval
    const rangeSegments = transcriptFetcher.getSegmentsInRange(transcript, 0, 60);
    console.log(`\n✓ Segments in first 60 seconds: ${rangeSegments.length}`);
    
  } catch (error) {
    console.error(`✗ Error: ${error.message}`);
  }
}

/**
 * Test error handling
 */
async function testErrorHandling() {
  console.log('\n🧪 Testing Error Handling...\n');
  
  const errorCases = [
    {
      name: 'Invalid video ID',
      url: 'https://www.youtube.com/watch?v=INVALIDID123',
      expectedError: 'not found'
    },
    {
      name: 'Invalid URL',
      url: 'not a url',
      expectedError: 'Invalid YouTube URL'
    }
  ];
  
  for (const testCase of errorCases) {
    console.log(`Testing: ${testCase.name}`);
    console.log(`URL: ${testCase.url}`);
    
    try {
      await youtubeApi.getVideoMetadata(testCase.url);
      console.log(`✗ Should have thrown error!`);
    } catch (error) {
      const hasExpectedError = error.message.toLowerCase().includes(testCase.expectedError.toLowerCase());
      console.log(`✓ Correctly threw error: ${error.message}`);
      console.log(`  Expected error type: ${hasExpectedError ? 'Yes' : 'No'}\n`);
    }
  }
}

/**
 * Run all tests
 */
async function runAllTests() {
  console.log('═══════════════════════════════════════════════════');
  console.log('   YouTube API & Transcript Fetcher Test Suite');
  console.log('═══════════════════════════════════════════════════');
  
  try {
    await testUrlParsing();
    await testMetadataFetching();
    await testTranscriptFetching();
    await testTranscriptSearch();
    await testErrorHandling();
    
    console.log('\n═══════════════════════════════════════════════════');
    console.log('   ✅ All tests completed!');
    console.log('═══════════════════════════════════════════════════\n');
    
  } catch (error) {
    console.error('\n❌ Fatal error during testing:');
    console.error(error);
    process.exit(1);
  }
}

// Run tests if this is the main module
runAllTests();
